spring.application.name=IOT-_distributed_sensor_system_whit_MQTT
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url=${URL_DB}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD_DB}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


mqtt.broker.url=tcp://test.mosquitto.org:1883
mqtt.topic=test5555868/topic
mqtt.client.id=mqttSpringClient
mqtt.qos=2

logging.level.root=info
logging.file.name=logs/app.log




scalar.theme=deepSpace
scalar.layout=modern
scalar.documentDownloadType=both