spring.application.name=IOT-_distributed_sensor_system_whit_MQTT

mqtt.broker.url=tcp://test.mosquitto.org:1883
mqtt.topic=test5555868/topic
mqtt.client.id=mqttSpringClient
mqtt.qos=2

logging.level.root=info
logging.file.name=logs/app.log